openapi: 3.0.1
info:
  description: Word Frequency API
  version: 1.0.0
  title: Word Frequency
  contact:
    email: en.varg@gmail.com
  license:
    name: private
tags:
  - name: WordFrequency
    description: Count words in file.
paths:
  /api/freqency:
    get:
      tags:
        - WordFrequency
      summary: Get word frequency in file
      description: >-
        Method get file path and K-word and return how many time K-word in text
      operationId: getFrequency
      parameters:
        - in: query
          required: true
          name: file
          schema:
            type: string
          description: Full path to file
        - in: query
          required: true
          name: word
          description: K-word to search
          schema:
            type: string
        - in: query
          required: false
          description: Ignore Case
          name: ignoreCase
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Response count word frequency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordFrequencyResponse'
        '400':
          description: Incorrect request
          content:
            application/json:
              example:
                timestamp: '2020-08-07T07:09:41.889+00:00'
                path: /api/frequency
                status: 400
                error: Bad Request
                message: 'Bad parameter file'
                requestId: "4121d29f-2949"
        '500':
          description: Internal error
          content:
            application/json:
              example:
                timestamp: '2020-08-07T07:09:41.889+00:00'
                path: /api/frequency
                status: 400
                error: Internal server error
                message: ''
    post:
      tags:
        - WordFrequency
      summary: Receive a file and count word frequency in file
      description: >-
        Method get K-word and receive file and return how many time K-word in text
      operationId: frequency
      parameters:
        - in: query
          required: true
          name: word
          description: K-word to search
          schema:
            type: string
        - in: query
          required: false
          description: Ignore Case
          name: ignoreCase
          schema:
            type: boolean
            default: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Some file. text-plain format.
            encoding:
              file:
                contentType: text/plain; charset=utf-8
      responses:
        '200':
          description: OK. Ответ содержит маппинги магазин-прейскурант.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordFrequencyResponse'
        '400':
          description: Incorrect request
          content:
            application/json:
              example:
                timestamp: '2020-08-07T07:09:41.889+00:00'
                path: /api/frequency
                status: 400
                error: Bad Request
                message: 'Bad parameter file'
        '500':
          description: Internal error
          content:
            application/json:
              example:
                timestamp: '2020-08-07T07:09:41.889+00:00'
                path: /api/frequency
                status: 400
                error: Internal server error
                message: ''
components:
  schemas:
    WordFrequencyResponse:
      type: object
      description: Model word frequency.
      properties:
        fileName:
          type: string
          example: '/home/app/some-file.txt'
          description: Full path and filename
        kWord:
          type: string
          example: 'awesome'
          description: Searched k-word
        frequency:
          type: integer
          example: 10
          description: How many time k-word found in text.